version: '3.4'

services:
  synapsenotes:
    image: synapsenotes
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  neo4j:
    image: neo4j:5.26.0
    ports:
      - 7474:7474
      - 7687:7687
    # environment:
    #   NEO4J_AUTH: neo4j/neo4j
    volumes:
      - ./neo4j/data:/data
      # - ./neo4j/logs:/logs
      # - ./neo4j/import:/var/lib/neo4j/import
      # - ./neo4j/plugins:/plugins